[tools]
bun = "latest"

[tasks.start]
run = "docker run --rm -it -p 3000:3000 -v $PWD:/work -w /work -v ~/.colima-jail/mise:/mise -v ~/.colima-jail/root:/root jdxcode/mise:latest x -- bun dev $MISE_ARG_1"

[tasks.format]
run = "bunx oxfmt@latest"

[tasks."format:check"]
run = "bunx oxfmt@latest --check"

[tasks."test:all"]
depends = ["test", "type-check", "client-compile", "format:check"]

[tasks.type-check]
depends = ["test"]
run = "bunx tsc --noEmit"

[tasks.test]
run = "bun test"

[tasks.client-compile]
run = "bun run build"
